[package]
name = "test-client"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
env_logger = "0.11.8"
log = "0.4.27"
tdtp-impl = { version = "0.1.0", path = "../tdtp-impl" , features = ["full"]}
time = { version = "0.3.41", features = ["std"] }
