[package]
name = "tdtp-impl"
version = "0.1.0"
edition = "2024"

[features]
client = []
server = []
full = ["client", "server"]

[dependencies]
derive_more = { version = "2.0.1", features = ["from"] }
log = "0.4.27"
tokio = { version = "1.47.1", features = ["macros"] }
